language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator image
    - sys-img-x86-android-29

before_install:
  - openssl aes-256-cbc -K $encrypted_f761570c4ae9_key -iv $encrypted_f761570c4ae9_iv -in app/google-services.json.enc -out app/google-services.json -d
  - android-wait-for-emulator
  - yes | sdkmanager "platforms;android-30"
  - chmod +x gradlew
