language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator image
    - android-22
    - sys-img-armeabi-v7a-android-22

before_install:
  # Google-service.json encrypted
  - openssl aes-256-cbc -K $encrypted_f761570c4ae9_key -iv $encrypted_f761570c4ae9_iv -in app/google-services.json.enc -out app/google-services.json -d
  # Google Play Console API key encrypted
  - openssl aes-256-cbc -K $encrypted_d6150d16fc0e_key -iv $encrypted_d6150d16fc0e_iv -in app/pc-api-6096031185577854460-416-6617465a8421.json.enc -out app/pc-api-6096031185577854460-416-6617465a8421.json -d
  # Keystore encrypted
  - openssl aes-256-cbc -K $encrypted_4f837f3546c7_key -iv $encrypted_4f837f3546c7_iv -in key.jks.enc -out key.jks -d
  - yes | sdkmanager "platforms;android-30"
  - chmod +x gradlew

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  # Get pass lock screen by sending a key event
  - adb shell input keyevent 82 &

script:
  - ./gradlew test
  - ./gradlew connectedAndroidTest
  - ./gradlew assembleRelease
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew publish; else ./gradlew build; fi
