language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator image
    - sys-img-x86-android-30

before_install:
    - chmod +x gradlew
