language: android
dist: trusty
env:
  global:
    - ANDROID_TARGET=android-30
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=10
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator image
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_install:
  # Lets not expose the google-service.json
  - openssl aes-256-cbc -K $encrypted_f761570c4ae9_key -iv $encrypted_f761570c4ae9_iv -in app/google-services.json.enc -out app/google-services.json -d
  - yes | sdkmanager "platforms;android-30"
  - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
